name: Windows Installer Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # --- NEW STEP: build OCR binary ---------------------------------
      - name: Build extract_rx.exe with PyInstaller
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller torch pillow opencv-python pytesseract
          pyinstaller --onefile extract_rx.py
          copy dist\\extract_rx.exe .
      # ----------------------------------------------------------------

      - name: Install npm deps
        run: npm ci   # faster than npm install

      - name: Package Electron app
        run: npm run make

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: m3dswft-installer
          path: out/make/squirrel.windows/x64/*.exe
